[versions]
compose-audio-controls = "0.7.1" # ourselves
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
foundation = "1.10.0"
kotlin = "2.3.0"
core-ktx = "1.17.0"
junit = "4.13.2"
kotlinx-coroutines-core = "1.10.2"
activity-compose = "1.12.2"
compose-bom = "2026.01.00"
dokka = "2.1.0"
ktmidi_version = "0.11.2"
compose-plugin = "1.10.0"
kotlinx-datetime = "0.7.1"
binary-compatibility-validator = "0.18.1"
material3 = "1.9.0"
materialSymbolsOutlinedFilledCmp = "2.2.1"
monitor = "1.8.0"
runtime = "1.10.0"
ui = "1.10.0"
vanniktech-maven-publish = "0.35.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ktmidi = { group = "dev.atsushieno", name = "ktmidi", version.ref = "ktmidi_version" }
ktmidi-jvm-desktop = { group = "dev.atsushieno", name = "ktmidi-jvm-desktop", version.ref = "ktmidi_version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
material-symbols-outlined-filled-cmp = { module = "com.composables:icons-material-symbols-outlined-filled-cmp", version.ref = "materialSymbolsOutlinedFilledCmp" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokkaPlugin = { id = "org.jetbrains.dokka", version.ref = "dokka" }
binaryCompatibilityValidatorPlugin = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
jetbrainsComposePlugin = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }

[bundles]
